#!/usr/bin/env python3
"""
SCENE-SYNC AGENT — lock motion-graphic scenes to the voiceover so graphics and words never drift.
Like caption.py, but for SCENES: it reads the VO word-level transcript and a scene spec, and emits
scenes.js (window.__SCENES) with exact start/end + a `peak` time per scene (when the climax — the
counted number / final bar / donut fill / line end — must land on the spoken keyword).

  python3 scripts/scene-sync.py <transcript.json> <spec.json> --offset 4.5 --total 58 --out projects/<name>

spec.json = ordered list of scenes. Each scene is either:
  - timed by VOICE:  {"anchor":"In just", "peak":"people", ...content}
       anchor = phrase whose FIRST word marks the scene start; peak = phrase whose LAST word the
       climax lands on. Scenes are made CONTIGUOUS (each ends where the next begins).
  - fixed:           {"fixed":[start,end], ...content}   (intro/outro, before/after the VO)
--offset = seconds added to transcript times (VO start delay). --total = full video length.

Result: graphics appear exactly while their line is spoken and climax on the exact word — no
single-frame drift. Re-run after any VO change; never hand-tune scene times again.
"""
import json, sys, argparse, re

def norm(w): return re.sub(r'[^a-z0-9]', '', w.lower())

def words_of(path):
    d = json.load(open(path))
    segs = d if isinstance(d, list) else d.get("segments", [])
    return [{"t": s["text"], "s": float(s["start"]), "e": float(s["end"])} for s in segs]

def find(words, phrase):
    toks = [norm(x) for x in phrase.split() if norm(x)]
    nw = [norm(w["t"]) for w in words]
    for i in range(len(nw) - len(toks) + 1):
        if nw[i:i+len(toks)] == toks:
            return words[i]["s"], words[i+len(toks)-1]["e"]
    sys.stderr.write(f"[scene-sync] WARNING: phrase not found: '{phrase}'\n")
    return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("transcript"); ap.add_argument("spec")
    ap.add_argument("--offset", type=float, default=0.0)
    ap.add_argument("--total", type=float, default=None)
    ap.add_argument("--lead", type=float, default=0.12, help="start each voiced scene slightly early")
    ap.add_argument("--out", default=".")
    a = ap.parse_args()

    words = words_of(a.transcript)
    spec = json.load(open(a.spec))
    O = a.offset

    # pass 1: resolve start + peak for each scene
    for sc in spec:
        if "fixed" in sc:
            sc["_s"], sc["_e_fixed"] = float(sc["fixed"][0]), float(sc["fixed"][1])
            sc["_peak"] = None
        else:
            r = find(words, sc["anchor"])
            sc["_s"] = (r[0] + O - a.lead) if r else 0.0
            if sc.get("peak"):
                p = find(words, sc["peak"])
                sc["_peak"] = (p[1] + O) if p else None
            else:
                sc["_peak"] = None

    # pass 2: make contiguous — each scene ends where the next begins
    out = []
    for i, sc in enumerate(spec):
        s = sc["_s"]
        if "fixed" in sc and sc.get("fixed"):
            e = sc["_e_fixed"]
        elif i + 1 < len(spec):
            e = spec[i+1]["_s"]
        else:
            e = a.total if a.total else (s + 6.0)
        o = {k: v for k, v in sc.items() if not k.startswith("_") and k not in ("anchor", "peak", "fixed")}
        o["s"] = round(s, 3); o["e"] = round(e, 3)
        if sc["_peak"] is not None: o["peak"] = round(sc["_peak"], 3)
        out.append(o)

    import os, tempfile
    os.makedirs(a.out, exist_ok=True)
    def _atomic(path, text):
        d = os.path.dirname(os.path.abspath(path)) or "."
        fd, tmp = tempfile.mkstemp(dir=d, suffix=".tmp")
        with os.fdopen(fd, "w") as f: f.write(text)
        os.replace(tmp, path)
    _atomic(os.path.join(a.out, "scenes.json"), json.dumps(out, ensure_ascii=False, indent=2))
    js = "/* scenes.js — generated by scripts/scene-sync.py. Times locked to the voiceover. */\nwindow.__SCENES = " + json.dumps(out, ensure_ascii=False) + ";\n"
    _atomic(os.path.join(a.out, "scenes.js"), js)
    print(f"[scene-sync] {len(out)} scenes -> {a.out}/scenes.js (+ scenes.json)")
    for o in out:
        pk = f" peak={o['peak']}" if "peak" in o else ""
        print(f"  {o.get('id','?'):10} {o['s']:>6} - {o['e']:<6}{pk}")

if __name__ == "__main__":
    main()
